"""
Script para adicionar colunas faltantes na tabela medications (PostgreSQL)
e recategorizar todos os medicamentos.
"""
import os
from sqlalchemy import text, inspect
from app import app, db
from models import Medication

# Mapeamento de categorias por nome
CATEGORIA_MAP = {
    'isotretinoina': 'sistemaico',
    'tretinoina': 'sistemaico',
    'clindamicina': 'antibiotico',
    'eritromicina': 'antibiotico',
    'doxiciclina': 'antibiotico',
    'minociclina': 'antibiotico',
    'azitromicina': 'antibiotico',
    'mupirocina': 'antibiotico',
    'fusidato de sodio': 'antibiotico',
    'fusidico': 'antibiotico',
    'acne': 'acne',
    'retinoide': 'sistemaico',
    'antibiotic': 'antibiotico',
    'antimicrob': 'antibiotico',
    'antifung': 'antifungico',
    'corticoide': 'corticoide',
    'hidrocortisona': 'corticoide',
    'betametasona': 'corticoide',
    'triancinolona': 'corticoide',
    'mometasona': 'corticoide',
    'desonida': 'corticoide',
    'dexametasona': 'corticoide',
    'pimecrolimus': 'imunomodulador',
    'tacrolimus': 'imunomodulador',
    'metotrexato': 'imunossupressor',
    'ciclosporina': 'imunossupressor',
    'azatioprina': 'imunossupressor',
    'hidroclorotiazida': 'diuretico',
    'furosemida': 'diuretico',
    'enalapril': 'cardiovascular',
    'losartana': 'cardiovascular',
    'amlodipina': 'cardiovascular',
    'atenolol': 'cardiovascular',
    'propanolol': 'cardiovascular',
    'hidroxicloroquina': 'imunomodulador',
    'colchicina': 'gota',
    'alopurinol': 'gota',
    'metformina': 'diabetes',
    'insulina': 'diabetes',
    'glicazida': 'diabetes',
    'levotiroxina': 'tireoide',
    'propiltiouracil': 'tireoide',
    'omeprazol': 'gastrointestinal',
    'pantoprazol': 'gastrointestinal',
    'ranitidina': 'gastrointestinal',
    'ondansetrona': 'gastrointestinal',
    'domperidona': 'gastrointestinal',
    'dipirona': 'analgesico',
    'paracetamol': 'analgesico',
    'ibuprofeno': 'analgesico',
    'celecoxibe': 'analgesico',
    'tramadol': 'analgesico',
    'codeina': 'analgesico',
    'amitriptilina': 'neurologico',
    'sertralina': 'neurologico',
    'fluoxetina': 'neurologico',
    'venlafaxina': 'neurologico',
    'pregabalina': 'neurologico',
    'gabapentina': 'neurologico',
    'carbamazepina': 'neurologico',
    'fenitoina': 'neurologico',
    'levetiracetam': 'neurologico',
    'topiramato': 'neurologico',
    'vitamina': 'vitamina',
    'acido folico': 'vitamina',
    'cianocobalamina': 'vitamina',
    'vit d': 'vitamina',
    'vit c': 'vitamina',
    'ferro': 'suplemento',
    'calcio': 'suplemento',
    'magnesio': 'suplemento',
    'zinco': 'suplemento',
    'selenio': 'suplemento',
    'acido': 'acido',
    'salicilico': 'acido',
    'glicolico': 'acido',
    'azonico': 'acido',
    'mandelico': 'acido',
    'lactico': 'acido',
    'tartarico': 'acido',
    'quinico': 'acido',
    'ferulico': 'acido',
    'azelaico': 'acido',
    'adapaleno': 'retinoides topicos',
    'benzoil': 'acne',
    'peroxido': 'acne',
    'azitro': 'antibiotico',
    'tetraciclina': 'antibiotico',
    'sulfametoxazol': 'antibiotico',
    'trimetoprim': 'antibiotico',
    'nitrofurantoina': 'antibiotico',
    'ciprofloxacino': 'antibiotico',
    'levofloxacino': 'antibiotico',
    'ofloxacino': 'antibiotico',
    'moxifloxacino': 'antibiotico',
    'polimixina': 'antibiotico',
    'bacitracina': 'antibiotico',
    'neomicina': 'antibiotico',
    'gentamicina': 'antibiotico',
    'tobramicina': 'antibiotico',
    'cistatina': 'antibiotico',
    'itraconazol': 'antifungico',
    'fluconazol': 'antifungico',
    'cetoconazol': 'antifungico',
    'miconazol': 'antifungico',
    'clotrimazol': 'antifungico',
    'nystatina': 'antifungico',
    'terbinafina': 'antifungico',
    'griseofulvina': 'antifungico',
    'ciclopirox': 'antifungico',
    'metronidazol': 'antibiotico',
    'tinidazol': 'antibiotico',
    'secnidazol': 'antibiotico',
    'ornidazol': 'antibiotico',
    'ivermectina': 'antiparasitario',
    'albendazol': 'antiparasitario',
    'mebendazol': 'antiparasitario',
    'praziquantel': 'antiparasitario',
    'permethrina': 'antiparasitario',
    'lindano': 'antiparasitario',
    'malation': 'antiparasitario',
    'sarnicida': 'antiparasitario',
    'escabiocida': 'antiparasitario',
    'podofilina': 'antiviral',
    'podofilox': 'antiviral',
    'imiquimod': 'imunomodulador',
    'interferon': 'antiviral',
    'aciclovir': 'antiviral',
    'valaciclovir': 'antiviral',
    'famciclovir': 'antiviral',
    'foscarnet': 'antiviral',
    'cidofovir': 'antiviral',
    'docosanol': 'antiviral',
    'penciclovir': 'antiviral',
    'trifluridina': 'antiviral',
    'idoxuridina': 'antiviral',
    'brivudina': 'antiviral',
    'foscarnet': 'antiviral',
    'caspofungina': 'antifungico',
    'anfotericina': 'antifungico',
    'voriconazol': 'antifungico',
    'posaconazol': 'antifungico',
    'isavuconazonio': 'antifungico',
    'ipilimumabe': 'imunoterapia',
    'nivolumabe': 'imunoterapia',
    'pembrolizumabe': 'imunoterapia',
    'atezolizumabe': 'imunoterapia',
    'durvalumabe': 'imunoterapia',
    'avelumabe': 'imunoterapia',
    'cemiplimabe': 'imunoterapia',
    'dostarlimabe': 'imunoterapia',
    'retifanlimabe': 'imunoterapia',
    'carboplatina': 'quimioterapia',
    'cisplatina': 'quimioterapia',
    'oxaliplatina': 'quimioterapia',
    '5-fluoruracil': 'quimioterapia',
    '5 fluoruracil': 'quimioterapia',
    'fluoruracil': 'quimioterapia',
    'metotrexato': 'quimioterapia',
    'bleomicina': 'quimioterapia',
    'dactinomicina': 'quimioterapia',
    'doxorrubicina': 'quimioterapia',
    'epirrubicina': 'quimioterapia',
    'idarubicina': 'quimioterapia',
    'mitoxantrona': 'quimioterapia',
    'vincristina': 'quimioterapia',
    'vinblastina': 'quimioterapia',
    'vinorelbina': 'quimioterapia',
    'paclitaxel': 'quimioterapia',
    'docetaxel': 'quimioterapia',
    'etoposideo': 'quimioterapia',
    'irinotecano': 'quimioterapia',
    'topotecano': 'quimioterapia',
    'gemcitabina': 'quimioterapia',
    'capecitabina': 'quimioterapia',
    'temozolomida': 'quimioterapia',
    'darbepoetina': 'suplemento',
    'eritropoetina': 'suplemento',
    'filgrastim': 'suplemento',
    'pegfilgrastim': 'suplemento',
    'sargramostim': 'suplemento',
    'oprelvequina': 'suplemento',
    'romiplostim': 'suplemento',
    'eltrombopague': 'suplemento',
    'avatrombopague': 'suplemento',
    'luspatercept': 'suplemento',
    'roxadustat': 'suplemento',
    'deferoxamina': 'suplemento',
    'deferasirox': 'suplemento',
    'deferiprona': 'suplemento',
    'edoxabana': 'cardiovascular',
    'rivaroxabana': 'cardiovascular',
    'apixabana': 'cardiovascular',
    'dabigatrana': 'cardiovascular',
    'warfarina': 'cardiovascular',
    'varfarina': 'cardiovascular',
    'heparina': 'cardiovascular',
    'enoxaparina': 'cardiovascular',
    'dalteparina': 'cardiovascular',
    'nadroparina': 'cardiovascular',
    'tinzaparina': 'cardiovascular',
    'bemiparina': 'cardiovascular',
    'fondaparinux': 'cardiovascular',
    'argatroban': 'cardiovascular',
    'lepirudina': 'cardiovascular',
    'desirudina': 'cardiovascular',
    'bivalirudina': 'cardiovascular',
    'fondaparinux': 'cardiovascular',
    'aspirina': 'analgesico',
    'acido acetilsalicilico': 'analgesico',
    'aas': 'analgesico',
    'clopidogrel': 'cardiovascular',
    'ticagrelor': 'cardiovascular',
    'prasugrel': 'cardiovascular',
    'ticlopidina': 'cardiovascular',
    'cilostazol': 'cardiovascular',
    'dipiridamol': 'cardiovascular',
    'cilostazol': 'cardiovascular',
    'pentoxifilina': 'cardiovascular',
    'cilostazol': 'cardiovascular',
    'trental': 'cardiovascular',
    'pentox': 'cardiovascular',
    'cilostazol': 'cardiovascular',
    'pletal': 'cardiovascular',
    'pentoxifilina': 'cardiovascular',
    'pentoxifilina': 'cardiovascular',
    'trental': 'cardiovascular',
    'captopril': 'cardiovascular',
    'ramipril': 'cardiovascular',
    'quinapril': 'cardiovascular',
    'perindopril': 'cardiovascular',
    'lisinopril': 'cardiovascular',
    'benazepril': 'cardiovascular',
    'fosinopril': 'cardiovascular',
    'moexipril': 'cardiovascular',
    'trandolapril': 'cardiovascular',
    'cilazapril': 'cardiovascular',
    'spirapril': 'cardiovascular',
    'zofenopril': 'cardiovascular',
    'imidapril': 'cardiovascular',
    'temocapril': 'cardiovascular',
    'delapril': 'cardiovascular',
    'spironolactona': 'diuretico',
    'eplerenona': 'diuretico',
    'canrenoato': 'diuretico',
    'canrenona': 'diuretico',
    'amilorida': 'diuretico',
    'triamtereno': 'diuretico',
    'torasemida': 'diuretico',
    'bumetanida': 'diuretico',
    'etacrinico': 'diuretico',
    'tienilico': 'diuretico',
    'indapamida': 'diuretico',
    'metolazona': 'diuretico',
    'clortalidona': 'diuretico',
    'clopamida': 'diuretico',
    'xipamida': 'diuretico',
    'meticlotiazida': 'diuretico',
    'politiazida': 'diuretico',
    'ciclotiazida': 'diuretico',
    'dichlorfenamida': 'diuretico',
    'acetazolamida': 'diuretico',
    'metazolamida': 'diuretico',
    'dorzolamida': 'diuretico',
    'brinzolamida': 'diuretico',
    'sulfonamida': 'diuretico',
    'sulfa': 'diuretico',
    'sulfadiazina': 'antibiotico',
    'sulfametizol': 'antibiotico',
    'sulfacetamida': 'acne',
    'sulfacetamida': 'acne',
    'sulfacetamida': 'acne',
    'colageno': 'suplemento',
    'acido hialuronico': 'suplemento',
    'hialuronico': 'suplemento',
    'peptideo': 'suplemento',
    'proteina': 'suplemento',
    'aminoacido': 'suplemento',
    'bcaa': 'suplemento',
    'glutamina': 'suplemento',
    'arginina': 'suplemento',
    'ornitina': 'suplemento',
    'citrulina': 'suplemento',
    'taurina': 'suplemento',
    'carnitina': 'suplemento',
    'creatina': 'suplemento',
    'betaina': 'suplemento',
    'fosfatidilserina': 'suplemento',
    'fosfatidilcolina': 'suplemento',
    'lecitina': 'suplemento',
    'inositol': 'suplemento',
    'colina': 'suplemento',
    'paba': 'suplemento',
    'biotina': 'vitamina',
    'vitamina a': 'vitamina',
    'vitamina e': 'vitamina',
    'vitamina k': 'vitamina',
    'vitamina b': 'vitamina',
    'b1': 'vitamina',
    'b2': 'vitamina',
    'b3': 'vitamina',
    'b5': 'vitamina',
    'b6': 'vitamina',
    'b7': 'vitamina',
    'b9': 'vitamina',
    'b12': 'vitamina',
    'niacina': 'vitamina',
    'acido pantotenico': 'vitamina',
    'piridoxina': 'vitamina',
    'tiamina': 'vitamina',
    'riboflavina': 'vitamina',
    'cobalamina': 'vitamina',
    'acido ascorbico': 'vitamina',
    'vitamina c': 'vitamina',
    'calciferol': 'vitamina',
    'colecalciferol': 'vitamina',
    'ergocalciferol': 'vitamina',
    'alfacalcidol': 'vitamina',
    'calcitriol': 'vitamina',
    'doxercalciferol': 'vitamina',
    'paricalcitol': 'vitamina',
    'vitamina e': 'vitamina',
    'alfa tocoferol': 'vitamina',
    'tocoferol': 'vitamina',
    'vitamina k': 'vitamina',
    'fitonadiona': 'vitamina',
    'menadiona': 'vitamina',
    'menaquinona': 'vitamina',
    'vitamina a': 'vitamina',
    'retinol': 'vitamina',
    'retinal': 'vitamina',
    'beta caroteno': 'vitamina',
    'betacaroteno': 'vitamina',
    'omega 3': 'suplemento',
    'omega3': 'suplemento',
    'epa': 'suplemento',
    'dha': 'suplemento',
    'oleo de peixe': 'suplemento',
    'oleo de krill': 'suplemento',
    'oleo de linhaca': 'suplemento',
    'acido graxo': 'suplemento',
    'gla': 'suplemento',
    'cla': 'suplemento',
    'msm': 'suplemento',
    'glucosamina': 'suplemento',
    'condroitina': 'suplemento',
    'cissus': 'suplemento',
    'quadrangularis': 'suplemento',
    'garcinia': 'suplemento',
    'cambogia': 'suplemento',
    'berberina': 'suplemento',
    'cromo': 'suplemento',
    'picolinato': 'suplemento',
    'inositol': 'suplemento',
    'd-chiro-inositol': 'suplemento',
    'myo-inositol': 'suplemento',
    'n-acetilcisteina': 'suplemento',
    'nac': 'suplemento',
    'glutationa': 'suplemento',
    'resveratrol': 'suplemento',
    'quercetina': 'suplemento',
    'curcumina': 'suplemento',
    'polifenol': 'suplemento',
    'catequina': 'suplemento',
    'egcg': 'suplemento',
    'luteina': 'suplemento',
    'zeaxantina': 'suplemento',
    'astaxantina': 'suplemento',
    'licopeno': 'suplemento',
    'fitoestrogeno': 'suplemento',
    'isoflavona': 'suplemento',
    'soja': 'suplemento',
    'ginseng': 'suplemento',
    'ashwagandha': 'suplemento',
    'rhodiola': 'suplemento',
    'bacopa': 'suplemento',
    'ginkgo': 'suplemento',
    'gotu kola': 'suplemento',
    'centella': 'suplemento',
    'camomila': 'suplemento',
    'melatonina': 'suplemento',
    'passiflora': 'suplemento',
    'valeriana': 'suplemento',
    'l-teanina': 'suplemento',
    '5-htp': 'suplemento',
    'sam-e': 'suplemento',
    'fosfatidilserina': 'suplemento',
    'uridina': 'suplemento',
    'citicolina': 'suplemento',
    'alfa-gpc': 'suplemento',
    'huperzina': 'suplemento',
    'lion mane': 'suplemento',
    'cordyceps': 'suplemento',
    'reishi': 'suplemento',
    'shiitake': 'suplemento',
    'maitake': 'suplemento',
    'turkey tail': 'suplemento',
    'agaricus': 'suplemento',
    'chaga': 'suplemento',
    'spirulina': 'suplemento',
    'chlorella': 'suplemento',
    'clorela': 'suplemento',
    'kombu': 'suplemento',
    'wakame': 'suplemento',
    'nori': 'suplemento',
    'dulse': 'suplemento',
    'arame': 'suplemento',
    'hiziki': 'suplemento',
    'kelp': 'suplemento',
    'fucus': 'suplemento',
    'laminaria': 'suplemento',
    'alga': 'suplemento',
    'espirulina': 'suplemento',
    'clorela': 'suplemento',
    'superfood': 'suplemento',
    'maca': 'suplemento',
    'guarana': 'suplemento',
    'yerba mate': 'suplemento',
    'cha verde': 'suplemento',
    'matcha': 'suplemento',
    'oolong': 'suplemento',
    'pu-erh': 'suplemento',
    'cha preto': 'suplemento',
    'cha branco': 'suplemento',
    'cha de': 'suplemento',
    'propolis': 'suplemento',
    'mel': 'suplemento',
    'geleia real': 'suplemento',
    'polen': 'suplemento',
    'apiculos': 'suplemento',
    'veneno': 'suplemento',
    'apiterapia': 'suplemento',
    'melatonina': 'suplemento',
    'serotonina': 'suplemento',
    'dopamina': 'suplemento',
    'norepinefrina': 'suplemento',
    'gaba': 'suplemento',
    'glutamato': 'suplemento',
    'glicina': 'suplemento',
    'alanina': 'suplemento',
    'serina': 'suplemento',
    'treonina': 'suplemento',
    'cisteina': 'suplemento',
    'metionina': 'suplemento',
    'lisina': 'suplemento',
    'histidina': 'suplemento',
    'arginina': 'suplemento',
    'aspartato': 'suplemento',
    'glutamina': 'suplemento',
    'prolina': 'suplemento',
    'fenilalanina': 'suplemento',
    'tirosina': 'suplemento',
    'triptofano': 'suplemento',
    'leucina': 'suplemento',
    'isoleucina': 'suplemento',
    'valina': 'suplemento',
    'bcaa': 'suplemento',
    'eaa': 'suplemento',
    'proteina': 'suplemento',
    'whey': 'suplemento',
    'caseina': 'suplemento',
    'soja': 'suplemento',
    'arroz': 'suplemento',
    'ervilha': 'suplemento',
    'cannabis': 'suplemento',
    'cbd': 'suplemento',
    'canabidiol': 'suplemento',
    'thc': 'suplemento',
    'tetrahidrocanabinol': 'suplemento',
    'canabidiol': 'suplemento',
    'oleo de cannabis': 'suplemento',
    'oleo de cbd': 'suplemento',
    'psilocibina': 'suplemento',
    'lsd': 'suplemento',
    'mdma': 'suplemento',
    'ketamina': 'suplemento',
    'ayahuasca': 'suplemento',
    'ibogaina': 'suplemento',
    'iboga': 'suplemento',
    'peyote': 'suplemento',
    'mescalina': 'suplemento',
    'dmt': 'suplemento',
    'bufo': 'suplemento',
    'sapo': 'suplemento',
    '5-meo-dmt': 'suplemento',
    'bufotenina': 'suplemento',
    'salvia': 'suplemento',
    'divinorum': 'suplemento',
    'kratom': 'suplemento',
    'mitragina': 'suplemento',
    'catuaba': 'suplemento',
    'damiana': 'suplemento',
    'maca peruana': 'suplemento',
    'tribulus': 'suplemento',
    'fenugreek': 'suplemento',
    'feno-grego': 'suplemento',
    'ashwagandha': 'suplemento',
    'maca': 'suplemento',
    'ginseng': 'suplemento',
    'rhodiola': 'suplemento',
    'schisandra': 'suplemento',
    'eleuterococo': 'suplemento',
    'siberiano': 'suplemento',
    'cordyceps': 'suplemento',
    'reishi': 'suplemento',
    'lion mane': 'suplemento',
    'chaga': 'suplemento',
    'turkey tail': 'suplemento',
    'maitake': 'suplemento',
    'shiitake': 'suplemento',
    'agaricus': 'suplemento',
    'royal sun': 'suplemento',
    'blazei': 'suplemento',
    'mesima': 'suplemento',
    'pleurotus': 'suplemento',
    'oyster': 'suplemento',
    'enoki': 'suplemento',
    'shimeji': 'suplemento',
    'nameko': 'suplemento',
    'buna-shimeji': 'suplemento',
    'hon-shimeji': 'suplemento',
    'maitake': 'suplemento',
    'hen of the woods': 'suplemento',
    'oyster mushroom': 'suplemento',
    'pleurotus ostreatus': 'suplemento',
    'king oyster': 'suplemento',
    'eryngii': 'suplemento',
    'pleurotus eryngii': 'suplemento',
    'oyster king': 'suplemento',
    'pleurotus nebrodensis': 'suplemento',
    'oyster nebrodensis': 'suplemento',
    'pleurotus citrinopileatus': 'suplemento',
    'golden oyster': 'suplemento',
    'pleurotus djamor': 'suplemento',
    'pink oyster': 'suplemento',
    'pleurotus salmoneo-stramineus': 'suplemento',
    'salmon oyster': 'suplemento',
    'pleurotus cornucopiae': 'suplemento',
    'branched oyster': 'suplemento',
    'pleurotus dryinus': 'suplemento',
    'veiled oyster': 'suplemento',
    'pleurotus pulmonarius': 'suplemento',
    'indian oyster': 'suplemento',
    'phoenix mushroom': 'suplemento',
    'pleurotus ostreatoroseus': 'suplemento',
    'rose oyster': 'suplemento',
    'pleurotus abalones': 'suplemento',
    'abalones': 'suplemento',
    'pleurotus cystidiosus': 'suplemento',
    'maple oyster': 'suplemento',
    'pleurotus euosmus': 'suplemento',
    'tarragon oyster': 'suplemento',
    'pleurotus fuscosquamulosus': 'suplemento',
    'scaly oyster': 'suplemento',
    'pleurotus griseus': 'suplemento',
    'grey oyster': 'suplemento',
    'pleurotus levis': 'suplemento',
    'smooth oyster': 'suplemento',
    'pleurotus ligilatus': 'suplemento',
    'ligate oyster': 'suplemento',
    'pleurotus membranaceus': 'suplemento',
    'membrane oyster': 'suplemento',
    'pleurotus ostreatus-jeju': 'suplemento',
    'jeju oyster': 'suplemento',
    'pleurotus porrigens': 'suplemento',
    "angel's wings": 'suplemento',
    'pleurotus pulmonarius-tmx1': 'suplemento',
    'tmx1 oyster': 'suplemento',
    'pleurotus sapidus': 'suplemento',
    'sapidus oyster': 'suplemento',
    'pleurotus smithii': 'suplemento',
    'smithii oyster': 'suplemento',
    'pleurotus spodoleucus': 'suplemento',
    'spodoleucus oyster': 'suplemento',
    'pleurotus tuber-regium': 'suplemento',
    'tuber oyster': 'suplemento',
    'pleurotus ultramariinus': 'suplemento',
    'ultramariinus oyster': 'suplemento',
}

INDICACAO_MAP = {
    'acne': 'acne',
    'espinha': 'acne',
    'comedao': 'acne',
    'cravo': 'acne',
    'seborreia': 'seborreia',
    'oleosidade': 'seborreia',
    'sebo': 'seborreia',
    'rosacea': 'rosacea',
    'eritema': 'rosacea',
    'couperose': 'rosacea',
    'melasma': 'melasma',
    'mancha': 'mancha',
    'hipercromia': 'mancha',
    'hipocromia': 'mancha',
    'clareamento': 'mancha',
    'pele': 'pele',
    'dermatite': 'dermatite',
    'eczema': 'eczema',
    'psoriase': 'psoriase',
    'vitiligo': 'vitiligo',
    'alopecia': 'alopecia',
    'calvicie': 'alopecia',
    'queda': 'alopecia',
    'cabelo': 'alopecia',
    'unha': 'unha',
    'onicomicose': 'unha',
    'verruga': 'verruga',
    'condiloma': 'verruga',
    'herpes': 'herpes',
    'zoster': 'herpes',
    'simples': 'herpes',
    'impetigo': 'impetigo',
    'foliculite': 'foliculite',
    'furunculo': 'furunculo',
    'abscesso': 'abscesso',
    'celulite': 'celulite',
    'erisipela': 'erisipela',
    'linfangite': 'linfangite',
    'micose': 'micose',
    'tinea': 'micose',
    'piedra': 'micose',
    'pitirase': 'pitirase',
    'liquen': 'liquen',
    'plano': 'liquen',
    'escleroso': 'liquen',
    'solar': 'solar',
    'queimadura': 'queimadura',
    'fotossensibilidade': 'fotossensibilidade',
    'protecao': 'protecao solar',
    'fps': 'protecao solar',
    'uv': 'protecao solar',
    'envelhecimento': 'anti-envelhecimento',
    'rugas': 'anti-envelhecimento',
    'flacidez': 'anti-envelhecimento',
    'cicatriz': 'cicatriz',
    'queloi': 'cicatriz',
    'hipertrofica': 'cicatriz',
    'prurido': 'prurido',
    'coceira': 'prurido',
    'urticaria': 'urticaria',
    'angioedema': 'urticaria',
    'edema': 'edema',
    'infeccao': 'infeccao',
    'bacteriana': 'infeccao',
    'viral': 'infeccao',
    'fungica': 'infeccao',
    'parasitaria': 'infeccao',
    'hanseniase': 'hanseniase',
    'tuberculose': 'tuberculose',
    'sifilis': 'sifilis',
    'gonorreia': 'gonorreia',
    'clamidia': 'clamidia',
    'hpv': 'hpv',
    'hiv': 'hiv',
    'aids': 'aids',
    'cancer': 'cancer',
    'carcinoma': 'cancer',
    'melanoma': 'melanoma',
    'basocelular': 'cancer',
    'espinocelular': 'cancer',
    'queratose': 'queratose',
    'actinica': 'queratose',
    'seborreica': 'queratose',
    'lentigo': 'lentigo',
    'nevo': 'nevo',
    'displasia': 'displasia',
    'epulis': 'epulis',
    'granuloma': 'granuloma',
    'piogenico': 'granuloma',
    'xantoma': 'xantoma',
    'sarcoidose': 'sarcoidose',
    'lupus': 'lupus',
    'dermatomiosite': 'dermatomiosite',
    'escleroderma': 'escleroderma',
    'esclerose': 'esclerose',
    'morphea': 'morphea',
    'calcinose': 'calcinose',
    'paniculite': 'paniculite',
    'panniculite': 'paniculite',
    'lipodistrofia': 'lipodistrofia',
    'acantose': 'acantose',
    'nigricans': 'acantose',
    'xerose': 'xerose',
    'ictiose': 'ictiose',
    'eritrodermia': 'eritrodermia',
    'exfoliativa': 'eritrodermia',
    'pustulose': 'pustulose',
    'acneiforme': 'acne',
    'dermatite': 'dermatite',
    'perioral': 'perioral',
    'seborreica': 'seborreia',
    'atopica': 'atopica',
    'contato': 'contato',
    'alergica': 'alergica',
    'irritativa': 'irritativa',
    'numular': 'numular',
    'estase': 'estase',
    'discoidal': 'discoidal',
    'photosen': 'fotossensibilidade',
    'solar': 'solar',
    'radia': 'radiacao',
    'termica': 'termica',
    'quimica': 'quimica',
    'eletrica': 'eletrica',
    'geladura': 'geladura',
    'congelamento': 'congelamento',
    'hipotermia': 'hipotermia',
    'hipertermia': 'hipertermia',
    'calor': 'calor',
    'suor': 'suor',
    'hiperidrose': 'hiperidrose',
    'bromidrose': 'bromidrose',
    'anhidrose': 'anhidrose',
    'miliaria': 'miliaria',
    'sudamina': 'sudamina',
    'intertrigo': 'intertrigo',
    'maceracao': 'maceracao',
    'erosao': 'erosao',
    'ulcera': 'ulcera',
    'fissura': 'fissura',
    'fistula': 'fistula',
    'sinus': 'sinus',
    'cisto': 'cisto',
    'quisto': 'cisto',
    'tumor': 'tumor',
    'nodulo': 'nodulo',
    'papula': 'papula',
    'vesicula': 'vesicula',
    'bolha': 'bolha',
    'pustula': 'pustula',
    'abcesso': 'abscesso',
    'carbunculo': 'carbunculo',
    'forunculo': 'furunculo',
    'hidradenite': 'hidradenite',
    'supurativa': 'supurativa',
    'acne inversa': 'acne inversa',
    'fox-fordyce': 'fox-fordyce',
    'miliaria': 'miliaria',
    'sudamina': 'sudamina',
}

def get_categoria(name, purpose):
    text = (name + ' ' + (purpose or '')).lower()
    for keyword, cat in CATEGORIA_MAP.items():
        if keyword in text:
            return cat
    return 'nao-categorizado'

def get_indicacoes(name, purpose):
    text = (name + ' ' + (purpose or '')).lower()
    inds = []
    for keyword, ind in INDICACAO_MAP.items():
        if keyword in text:
            if ind not in inds:
                inds.append(ind)
    return inds if inds else ['geral']

def add_columns():
    """Adiciona colunas faltantes no PostgreSQL."""
    with app.app_context():
        inspector = inspect(db.engine)
        cols = [c['name'] for c in inspector.get_columns('medications')]
        
        print('Colunas atuais em medications:', cols)
        
        if 'categoria' not in cols:
            db.session.execute(text("ALTER TABLE medications ADD COLUMN categoria VARCHAR(100)"))
            print('ADD COLUMN categoria')
        if 'indicacoes' not in cols:
            db.session.execute(text("ALTER TABLE medications ADD COLUMN indicacoes JSON"))
            print('ADD COLUMN indicacoes')
        if 'etiqueta_revisada' not in cols:
            db.session.execute(text("ALTER TABLE medications ADD COLUMN etiqueta_revisada BOOLEAN DEFAULT FALSE"))
            print('ADD COLUMN etiqueta_revisada')
        
        db.session.commit()
        print('Colunas adicionadas com sucesso!')

def categorize_all():
    """Categoriza todos os medicamentos."""
    with app.app_context():
        meds = Medication.query.all()
        count = 0
        for m in meds:
            if not m.categoria:
                m.categoria = get_categoria(m.name, m.purpose)
                m.indicacoes = get_indicacoes(m.name, m.purpose)
                m.etiqueta_revisada = False
                count += 1
        db.session.commit()
        print(f'Categorizados {count} de {len(meds)} medicamentos.')
        
        # Resumo
        from sqlalchemy import func
        cats = db.session.query(Medication.categoria, func.count(Medication.id)).group_by(Medication.categoria).all()
        print('\nResumo por categoria:')
        for cat, cnt in sorted(cats, key=lambda x: -x[1]):
            print(f'  {cat}: {cnt}')

if __name__ == '__main__':
    add_columns()
    categorize_all()
    print('\nDone!')
