"""expand surgery evolution followup fields

Revision ID: 4fc309ae60d0
Revises: 
Create Date: 2026-03-09 16:50:16.308349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc309ae60d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_appointment_doctor_date'))
        batch_op.drop_index(batch_op.f('idx_appointment_start_time'))

    with op.batch_alter_table('cosmetic_procedure_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cosmetic_procedure_plan_note'))

    with op.batch_alter_table('evolution', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_evolution_evolution_date'))
        batch_op.drop_index(batch_op.f('idx_evolution_patient_id'))
        batch_op.create_index(batch_op.f('ix_evolution_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_evolution_date'), ['evolution_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('follow_up_reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_follow_up_reminder_patient_procedure'))
        batch_op.drop_index(batch_op.f('idx_follow_up_reminder_status'))

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_indication_note'))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_note_patient_category'))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('surgery_evolution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_folliculitis_acute', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_folliculitis_chronic', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_rarefaction', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_local_failure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('patient_satisfied', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('result_within_expected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('using_oral_medication', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_body_hair', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('needs_touch_up', sa.Boolean(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_surgery_evolution_created_at'))
        batch_op.drop_index(batch_op.f('idx_surgery_evolution_date'))
        batch_op.drop_index(batch_op.f('idx_surgery_evolution_surgery_id'))
        batch_op.create_index(batch_op.f('ix_surgery_evolution_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_surgery_evolution_evolution_date'), ['evolution_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_surgery_evolution_surgery_id'), ['surgery_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('surgery_evolution_surgery_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'transplant_surgery_record', ['surgery_id'], ['id'])

    with op.batch_alter_table('transplant_surgery_record', schema=None) as batch_op:
        batch_op.drop_column('calendar_event_id')
        batch_op.drop_column('status')
        batch_op.drop_column('planning_snapshot')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_username'))
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index(batch_op.f('idx_user_username'), ['username'], unique=True)

    with op.batch_alter_table('transplant_surgery_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_snapshot', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('calendar_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('surgery_evolution', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('surgery_evolution_surgery_id_fkey'), 'transplant_surgery_record', ['surgery_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_surgery_evolution_surgery_id'))
        batch_op.drop_index(batch_op.f('ix_surgery_evolution_evolution_date'))
        batch_op.drop_index(batch_op.f('ix_surgery_evolution_created_at'))
        batch_op.create_index(batch_op.f('idx_surgery_evolution_surgery_id'), ['surgery_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_surgery_evolution_date'), ['evolution_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_surgery_evolution_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('needs_touch_up')
        batch_op.drop_column('needs_body_hair')
        batch_op.drop_column('using_oral_medication')
        batch_op.drop_column('result_within_expected')
        batch_op.drop_column('patient_satisfied')
        batch_op.drop_column('has_local_failure')
        batch_op.drop_column('has_rarefaction')
        batch_op.drop_column('has_folliculitis_chronic')
        batch_op.drop_column('has_folliculitis_acute')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('appointment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_note_patient_category'), ['patient_id', 'category'], unique=False)

    with op.batch_alter_table('indication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_indication_note'), ['note_id'], unique=False)

    with op.batch_alter_table('follow_up_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_follow_up_reminder_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_follow_up_reminder_patient_procedure'), ['patient_id', 'procedure_name'], unique=False)

    with op.batch_alter_table('evolution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_patient_id'))
        batch_op.drop_index(batch_op.f('ix_evolution_evolution_date'))
        batch_op.drop_index(batch_op.f('ix_evolution_created_at'))
        batch_op.create_index(batch_op.f('idx_evolution_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_evolution_evolution_date'), ['evolution_date'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('cosmetic_procedure_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cosmetic_procedure_plan_note'), ['note_id'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_appointment_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('idx_appointment_doctor_date'), ['doctor_id', 'start_time'], unique=False)

    # ### end Alembic commands ###
